In [2]:
import pandas as pd

In [2]:
mvps = pd.read_csv('mvps.csv')

In [3]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
482,8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
483,9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
484,10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
485,11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [4]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [5]:
mvps.head()

            Player  Year  Pts Won  Pts Max  Share
0   Michael Jordan  1991    891.0      960  0.928
1    Magic Johnson  1991    497.0      960  0.518
2   David Robinson  1991    476.0      960  0.496
3  Charles Barkley  1991    222.0      960  0.231
4      Karl Malone  1991    142.0      960  0.148

In [6]:
players = pd.read_csv("players.csv")

In [7]:
players

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18193,836,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
18194,837,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
18195,838,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
18196,839,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
18197,840,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [8]:
del players["Unnamed: 0"]
del players["Rk"]
players["Player"] = players["Player"].str.replace("*","", regex=False)
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,0.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,0.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,0.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,0.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,0.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [9]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,0.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,0.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,0.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
449,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,0.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1358,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,0.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1838,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,0.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2289,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,0.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2836,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,0.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3408,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,0.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [10]:
def single_team(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"]=="TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_team)

In [11]:
players

                                  Player Pos  Age   Tm   G  GS    MP   FG  \
Player         Year
A.C. Green     1991 159       A.C. Green  PF   27  LAL  82  21  26.4  3.1
               1992 609       A.C. Green  PF   28  LAL  82  53  35.4  4.7
               1993 1051      A.C. Green  PF   29  LAL  82  55  34.4  4.6
               1994 1519      A.C. Green  PF   30  PHO  82  55  34.5  5.7
               1995 1988      A.C. Green  SF   31  PHO  82  52  32.8  3.8
...                                  ...  ..  ...  ...  ..  ..   ...  ...
Željko Rebrača 2002 5866  Željko Rebrača   C   29  DET  74   4  15.9  2.6
               2003 6347  Željko Rebrača   C   30  DET  30  12  16.3  2.7
               2004 6907  Željko Rebrača   C   31  ATL  24   2  11.4  1.4
               2005 7485  Željko Rebrača   C   32  LAC  58   2  16.0  2.3
               2006 8057  Željko Rebrača   C   33  LAC  29   2  14.2  1.8

                           FGA    FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV  \
Player         Year                    ...
A.C. Green     1991 159    6.6  0.476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2
               1992 609    9.8  0.476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4
               1993 1051   8.6  0.537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4
               1994 1519  11.3  0.502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2
               1995 1988   7.5  0.504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4
...                        ...    ...  ...  ...  ...  ...  ...  ...  ...  ...
Željko Rebrača 2002 5866   5.1  0.505  ...  1.1  2.8  3.9  0.5  0.4  1.0  1.1
               2003 6347   4.8  0.552  ...  0.9  2.2  3.1  0.3  0.2  0.6  1.0
               2004 6907   3.2  0.442  ...  1.0  1.5  2.4  0.3  0.2  0.5  0.7
               2005 7485   4.0  0.568  ...  0.8  2.3  3.2  0.4  0.2  0.7  0.8
               2006 8057   3.3  0.542  ...  0.4  1.8  2.2  0.3  0.2  0.7  0.8

                           PF   PTS  Year
Player         Year
A.C. Green     1991 159   1.4   9.1  1991
               1992 609   1.7  13.6  1992
               1993 1051  1.8  12.8  1993
               1994 1519  1.7  14.7  1994
               1995 1988  1.8  11.2  1995
...                       ...   ...   ...
Željko Rebrača 2002 5866  2.6   6.9  2002
               2003 6347  2.6   6.6  2003
               2004 6907  2.2   3.8  2004
               2005 7485  2.2   5.8  2005
               2006 8057  2.0   4.7  2006

[14697 rows x 30 columns]

In [12]:
players.index = players.index.droplevel()
players.index = players.index.droplevel()
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
159,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
609,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,0.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1051,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,0.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1519,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,0.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
1988,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,0.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995

In [13]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,0.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
449,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,0.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1358,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,0.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1838,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,0.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2289,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,0.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2836,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,0.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3408,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,0.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [14]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [15]:
combined[combined["Pts Won"] > 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
197,Al Jefferson,C,29,CHA,73,73,35.0,9.6,18.8,0.509,...,2.1,0.9,1.1,1.7,2.4,21.8,2014,34.0,1250.0,0.027
346,Allen Iverson,PG,21,PHI,76,74,40.1,8.2,19.8,0.416,...,7.5,2.1,0.3,4.4,3.1,23.5,1997,1.0,1150.0,0.001
348,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,0.412,...,4.6,2.3,0.1,3.5,2.0,26.8,1999,319.0,1180.0,0.270
349,Allen Iverson,SG,24,PHI,70,70,40.8,10.4,24.8,0.421,...,4.7,2.1,0.1,3.3,2.3,28.4,2000,132.0,1210.0,0.109
350,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,0.420,...,4.6,2.5,0.3,3.3,2.1,31.1,2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14170,Vince Carter,SF,23,TOR,82,82,38.1,9.6,20.7,0.465,...,3.9,1.3,1.1,2.2,3.2,25.7,2000,51.0,1210.0,0.042
14171,Vince Carter,SF,24,TOR,75,75,39.7,10.2,22.1,0.460,...,3.9,1.5,1.1,2.2,2.7,27.6,2001,7.0,1240.0,0.006
14175,Vince Carter,SF-SG,28,NJN,77,76,36.7,9.0,20.0,0.452,...,4.2,1.4,0.6,2.2,3.2,24.5,2005,3.0,1270.0,0.002
14549,Yao Ming,C,23,HOU,82,82,32.8,6.5,12.5,0.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
14554,Yao Ming,C,28,HOU,77,77,33.6,7.4,13.4,0.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001

In [16]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,0.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,0.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,0.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,0.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,0.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,NaN,NaN,NaN
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,0.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,0.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,NaN,NaN,NaN
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,0.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,0.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN

In [17]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,0.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,0.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,0.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,0.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,0.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,0.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,0.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,0.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,0.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [18]:
teams = pd.read_csv("teams.csv")
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,0.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,0.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,0.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,0.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,0.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
931,13,56,26,0.683,—,115.6,109.9,5.37,2022,Memphis Grizzlies*
932,14,52,30,0.634,4.0,108.0,104.7,3.12,2022,Dallas Mavericks*
933,15,36,46,0.439,20.0,109.3,110.3,-0.84,2022,New Orleans Pelicans*
934,16,34,48,0.415,22.0,113.2,113.0,0.02,2022,San Antonio Spurs
935,17,20,62,0.244,36.0,109.7,118.2,-8.26,2022,Houston Rockets

In [19]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [20]:
sorted(teams["Team"].unique())

['Atlanta Hawks',
 'Boston Celtics',
 'Brooklyn Nets',
 'Charlotte Bobcats',
 'Charlotte Hornets',
 'Chicago Bulls',
 'Cleveland Cavaliers',
 'Dallas Mavericks',
 'Denver Nuggets',
 'Detroit Pistons',
 'Golden State Warriors',
 'Houston Rockets',
 'Indiana Pacers',
 'Los Angeles Clippers',
 'Los Angeles Lakers',
 'Memphis Grizzlies',
 'Miami Heat',
 'Milwaukee Bucks',
 'Minnesota Timberwolves',
 'New Jersey Nets',
 'New Orleans Hornets',
 'New Orleans Pelicans',
 'New Orleans/Oklahoma City Hornets',
 'New York Knicks',
 'Oklahoma City Thunder',
 'Orlando Magic',
 'Philadelphia 76ers',
 'Phoenix Suns',
 'Portland Trail Blazers',
 'Sacramento Kings',
 'San Antonio Spurs',
 'Seattle SuperSonics',
 'Toronto Raptors',
 'Utah Jazz',
 'Vancouver Grizzlies',
 'Washington Bullets',
 'Washington Wizards']

In [21]:
sorted(combined["Tm"].unique())

['ATL',
 'BOS',
 'BRK',
 'CHA',
 'CHH',
 'CHI',
 'CHO',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOH',
 'NOK',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHO',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS',
 'WSB']

In [22]:
nicknames = {}
with open("Data/shortnames.txt") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev,name = line.replace("\n","").split(",")
        nicknames[abbrev] = name

In [23]:
combined["Team"] = combined["Tm"].map(nicknames)

In [24]:
train = combined.merge(teams, how="outer",on=["Team", "Year"])

In [25]:
train

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.0,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0.0,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0.0,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0.0,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.0,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0.0,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45
14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0.0,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45
14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0.0,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45
14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0.0,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45
14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0.0,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45

In [26]:
del train["Unnamed: 0"]

In [27]:
train.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [28]:
train = train.apply(pd.to_numeric, errors='ignore')

In [29]:
train.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [30]:
train["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '—', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '1.0', '13.0', '17.0', '3.0', '15.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '50.0', '10.0', '30.0',
       '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '43.0', '39.0',
       '18.5', '31.0', '48.0', '46.0', '10.5', '32.0', '38.0', '27.0',
       '33.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5', '4.5'],
      dtype=object)

In [31]:
train["GB"] = pd.to_numeric(train["GB"].str.replace('—','0'))

In [32]:
train.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [33]:
import pandas as pd

In [34]:
pd.isnull(train).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          59
3P            0
3PA           0
3P%        2086
2P            0
2PA           0
2P%         100
eFG%         59
FT            0
FTA           0
FT%         521
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [35]:
train[pd.isnull(train["3P%"])][["Player", "3PA"]].head()

             Player  3PA
2    Elden Campbell  0.0
3     Irving Thomas  0.0
18       Jack Haley  0.0
20      Keith Owens  0.0
30  Benoit Benjamin  0.0

In [36]:
train[pd.isnull(train["FT%"])][["Player", "FTA"]].head()

              Player  FTA
77        John Coker  0.0
92      Jason Sasser  0.0
103  Adrian Caldwell  0.0
119     Bruno Šundov  0.0
158   Jamal Robinson  0.0

In [37]:
train = train.fillna(0)

In [38]:
train.to_csv("player_mvp_stats.csv")

In [3]:
stats2 = pd.read_csv("Data_Stats.csv", index_col=0)

In [5]:
stats2.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,dbpm,bpm,vorp,mov,mov_adj,_ID_NEW,Level_of_Impact,Quality_of_Impact,Wins_Contribution,Total_Stats
Column1,,,,,,,,,,,,,,,,,,,,,
143,Shaquille O'Neal,C,27,LAL,79,79,40.0,12.1,21.1,0.574,...,2.0,9.3,9.0,8.55,8.41,1,16.782683,17.16,287.990839,119.089656
641,Nikola Jokić,C,25,DEN,72,72,34.6,10.2,18.0,0.566,...,3.0,12.1,8.8,4.93,4.82,2,8.805278,16.02,141.060554,113.531904
663,Nikola Jokić,C,26,DEN,74,74,33.5,10.3,17.7,0.583,...,4.5,13.7,9.8,2.30,2.16,3,9.643915,16.56,159.703226,130.160376
929,James Harden,SG,28,HOU,72,72,35.4,9.0,20.1,0.449,...,1.4,9.9,7.7,8.48,8.21,4,15.195018,15.20,230.964278,102.463488
1030,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,0.420,...,1.1,6.1,6.1,4.28,3.63,5,15.231232,11.96,182.165531,69.352232

In [7]:
stats2.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Share Pts Won', 'Share Pts Max', 'Share pc', 'Team', 'Team W',
       'Team L', 'Team WL', 'Team GB', 'Team PS G', 'Team PA G', 'Team P Diff',
       'PTS_R', 'AST_R', 'STL_R', 'BLK_R', '3P_R', 'NPos', 'NTm',
       'Point_Contribution_PG', 'Rank_MVP', 'per', 'ts_pct',
       'fg3a_per_fga_pct', 'fta_per_fga_pct', 'orb_pct', 'drb_pct', 'trb_pct',
       'ast_pct', 'stl_pct', 'blk_pct', 'tov_pct', 'usg_pct', 'ows', 'dws',
       'ws', 'ws_per_48', 'obpm', 'dbpm', 'bpm', 'vorp', 'mov', 'mov_adj',
       '_ID_NEW', 'Level_of_Impact', 'Quality_of_Impact', 'Wins_Contribution',
       'Total_Stats'],
      dtype='object')

In [10]:
pd.set_option('display.max_columns', None)

In [13]:
pd.set_option('display.max_rows', 500)

In [15]:
pd.isnull(stats2).sum()

Player                   0
Pos                      0
Age                      0
Tm                       0
G                        0
GS                       0
MP                       0
FG                       0
FGA                      0
FG%                      0
3P                       0
3PA                      0
3P%                      0
2P                       0
2PA                      0
2P%                      0
eFG%                     0
FT                       0
FTA                      0
FT%                      0
ORB                      0
DRB                      0
TRB                      0
AST                      0
STL                      0
BLK                      0
TOV                      0
PF                       0
PTS                      0
Year                     0
Share Pts Won            0
Share Pts Max            0
Share pc                 0
Team                     0
Team W                   0
Team L                   0
Team WL                  0
Team GB                  0
Team PS G                0
Team PA G                0
Team P Diff              0
PTS_R                    0
AST_R                    0
STL_R                    0
BLK_R                    0
3P_R                     0
NPos                     0
NTm                      0
Point_Contribution_PG    2
Rank_MVP                 0
per                      0
ts_pct                   0
fg3a_per_fga_pct         0
fta_per_fga_pct          0
orb_pct                  0
drb_pct                  0
trb_pct                  0
ast_pct                  0
stl_pct                  0
blk_pct                  0
tov_pct                  0
usg_pct                  0
ows                      0
dws                      0
ws                       0
ws_per_48                0
obpm                     0
dbpm                     0
bpm                      0
vorp                     0
mov                      0
mov_adj                  0
_ID_NEW                  0
Level_of_Impact          0
Quality_of_Impact        0
Wins_Contribution        0
Total_Stats              0
dtype: int64